version: '3.8'

services:
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
            - ./project/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: 'fairy_tale_factory'
            MYSQL_ROOT_PASSWORD: 'llll'
        ports:
            - "3307:3306"
    web:
        build: .
        command: python manage.py runserver 127.0.0.1:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    db_data:
